### ISSUE TITLE
Neo4j Input Exception

### ISSUE THREAD

**Issue by nilskre** [saezlab/CKG-BioCypher#2]
First of all thanks a lot for this project!

When trying to import the generated CSV files into Neo4j, the process fails with ```org.neo4j.internal.batchimport.input.InputException: ERROR in input``` ... ```there's a field starting with a quote and whereas it ends that quote there seems to be characters in that field after that ending quote. That isn't supported. This is what I read: 'Carrion's'```

Proposed solution: remove ```'``` from the input.

**Comment by slobentanzer** [comment]
Hi @nilskre,
thanks for the report! Did you try setting the quote character to double quotes instead of single ones? I.e. `biocypher_config.yaml` (the one you are using in the script):
```
neo4j:
  quote_character: '"'
```

Maybe I forgot adding that after the last update. For me, using the double quote works.

**Comment by nilskre** [comment]
Hi @slobentanzer,
thanks for the fast and helpful response! I did not know, that this config option exists. With this config, it works without any problems. Thanks for fixing it by the [commit](https://github.com/biocypher/clinical-knowledge-graph/commit/147942a4faa416c1e58f919cbf65568514123fe9). 
One final question here: Was it intended to only add this to [one](https://github.com/biocypher/clinical-knowledge-graph/blob/main/config/biocypher_config_full.yaml) of the three config files? Maybe this can cause confusion because 
this option is still missing in the [subset](https://github.com/biocypher/clinical-knowledge-graph/blob/main/config/biocypher_config_subset.yaml) and [embedding](https://github.com/biocypher/clinical-knowledge-graph/blob/main/config/biocypher_config_embedding.yaml) config. Or am I missing something?
Thanks in advance!

**Comment by slobentanzer** [comment]
No, you're completely right. I updated the code recently for a new version of BioCypher, and did not add the config option. Thanks for the report. :)
