### ISSUE TITLE
Suggestion of some minor readme improvements

### ISSUE THREAD

**Issue by nilskre** [saezlab/CKG-BioCypher#4]
Hey,

thanks again for this great project. 

This is not really an issue, this is instead some feedback on the Readme. 
May I suggest some minor Readme improvements here? While testing the Full import and Subsetting procedures some potential ambiguities came up for me. This is only based on my personal experience when trying it out. So it may also be the case, that this was only unclear to me (and clear for everybody else).

- I really like the short and precise form of the Readme.
- Maybe the point, that the CKG must be running in a Neo4j instance can be emphasized a little bit more (e.g. by also including the [link](https://ckg.readthedocs.io/en/latest/ckg_builder/graphdb-builder.html#building-ckg-s-graph-database-from-a-dump-file) how to set it up)
- The credentials for the running CKG Neo4j instance need to be inserted [in the adapter](https://github.com/biocypher/clinical-knowledge-graph/blob/main/ckgb/adapter.py#L37). For me, it would have been helpful to point out, where to insert the credentials. In the beginning, I was confused and tried to insert them into the [biocypher_config.yaml](https://github.com/biocypher/clinical-knowledge-graph/blob/main/config/biocypher_config_full.yaml).
- For the subsetting procedure it would have been helpful to mention, that the subset nodes/edges need to be present in the [data files](https://github.com/biocypher/clinical-knowledge-graph/tree/main/data). In my first try, I only adapted the schema and wondered, that it was not successful.
- Some pointers in the right direction on how/where to adapt the code to insert node and edge properties could be helpful.

**Comment by slobentanzer** [comment]
Hi @nilskre,
thanks a lot for your input! Since you are close to the matter, having just tried it, do you want to file a PR to the README with your proposed changes? I'll happily review and merge that. :)

**Comment by nilskre** [comment]
Alright, thanks. I will propose a PR for this (:
